### ISSUE TITLE
confusion about model&corpus

### ISSUE THREAD

**Issue by ScottLiao920** [hassyGo/NLG-RL#1]
Hi Kazuma, 
I read your code in train_vocgen.py, but I found the "data/corpus" and "model/vocgen" are missing. May I know what's inside and how to use your code for nlg?
Thanks for reading.

**Comment by hassyGo** [comment]
Hello

Thank you for your question.
It seems you already resolved your question by yourself, but basically these files need to be prepared by you.

If you have further questions, let me know.

Thanks

**Comment by ScottLiao920** [comment]
> Hello
> 
> Thank you for your question.
> It seems you already resolved your question by yourself, but basically these files need to be prepared by you.
> 
> If you have further questions, let me know.
> 
> Thanks

Just a small problem.
In code_0.4/data line 189. 
There should be a train arg for the method to load dev/train data, am I right?
